export enum ISetting {
  "MAX_WITHDRAW_CRYPTO_CURRENCY" = "maxWithdrawCrypto",
"WITHDRAW_FIAT_MANAGER_CONFIRMATION" = "withdraFiatConfirm",
"MAX_WITHDRAW_FIAT" = "maxWithdrawFiat",
"WITHDRAW_FIAT_CURRENCY_INTERFACE" = "withdrawFiat",
"WITHDRAW_CRYPTO_CURRENCY_CURRENCY_INTERFACE" = "withdrawCrypto",
"WITHDRAW_CRYPTO_CURRENCY_MANAGER_CONFIRMATION" = "withdraCryptoConfirm"
}
